version: "3"
services:
  hmpps-incentives-api:
    build: .
    networks:
      - hmpps
    container_name: hmpps-incentives-api
    depends_on:
      - hmpps-auth
      - incentives-db
      - localstack
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "wget", "--tries=1", "--spider", "http://localhost:8080/health"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev,localstack
      - HMPPS_SQS_LOCALSTACK_URL=http://localstack:4566
      - API_BASE_URL_OAUTH=http://hmpps-auth:8080/auth
      - API_BASE_URL_PRISON=http://prison-api-incentives-api:8080
      - API_BASE_URL_OFFENDER_SEARCH=http://prisoner-search:8080
      - SPRING_FLYWAY_URL=jdbc:postgresql://incentives-db:5432/incentives?sslmode=prefer
      - SPRING_R2DBC_URL=r2dbc:postgresql://incentives-db:5432/incentives?sslmode=prefer
      - INCENTIVES_API_CLIENT_ID=omicadmin
      - INCENTIVES_API_CLIENT_SECRET=clientsecret
    links:
      - localstack:egress.localstack
      - localstack:dev-ingress-archive-hmpps-incentives-api.localstack
      - localstack:dev-ingress-hmpps-incentives-api.localstack

  hmpps-auth:
    image: quay.io/hmpps/hmpps-auth:latest
    networks:
      - hmpps
    container_name: hmpps-auth-incentives-api
    ports:
      - "9090:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/health"]
    environment:
      - SPRING_PROFILES_ACTIVE=dev,nomis
      - APPLICATION_AUTHENTICATION_UI_ALLOWLIST=0.0.0.0/0
      - NOMIS_ENDPOINT_URL=http://nomis-user-roles-api-incentives-api:8080

  nomis-user-roles-api:
    image: quay.io/hmpps/nomis-user-roles-api:latest
    networks:
      - hmpps
    container_name: nomis-user-roles-api-incentives-api
    depends_on:
      - hmpps-auth
    ports:
      - "8084:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
      - API_BASE_URL_OAUTH=http://hmpps-auth:8080/auth

  prisoner-search:
    image: wiremock/wiremock:2.35.0
    networks:
      - hmpps
    container_name: prisoner-search
    ports:
      - "8083:8080"
    volumes:
      - ./prisoner-search-data:/home/wiremock

  prison-api:
    image: quay.io/hmpps/prison-api:latest
    networks:
      - hmpps
    container_name: prison-api-incentives-api
    depends_on:
      - hmpps-auth
    ports:
      - "8082:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/health"]
    environment:
      - SPRING_PROFILES_ACTIVE=nomis-hsqldb

  incentives-db:
    image: postgres
    networks:
      - hmpps
    # network_mode: "host"
    container_name: incentives-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=incentives
      - POSTGRES_USER=incentives
      - POSTGRES_DB=incentives

  localstack:
    image: localstack/localstack:2.3
    networks:
      - hmpps
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack}"
    ports:
      - "4566:4566"
      - "8999:8080"
    environment:
      - DEBUG=${DEBUG- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME=${LOCALSTACK_DOCKER_NAME-localstack}
      - HOSTNAME_EXTERNAL=${LOCALSTACK_DOCKER_NAME-localstack}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  hmpps:
