version: "3"
services:
  localstack:
    image: localstack/localstack:1.2
    networks:
      - hmpps
    container_name: localstack
    ports:
      - "4566-4597:4566-4597"
      - "8999:8080"
    environment:
      - DEBUG=${DEBUG- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=eu-west-2
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-/tmp/localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  incentives-db:
    image: postgres
    networks:
      - hmpps
    container_name: incentives-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=incentives
      - POSTGRES_USER=incentives
      - POSTGRES_DB=incentives

networks:
  hmpps:
