services:

  localstack:
    image: localstack/localstack:4
    networks:
      - hmpps
    container_name: inc-localstack
    ports:
      - "4566:4566"
      - "8999:8080"
    environment:
      - DEBUG=${DEBUG- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  incentives-db:
    image: postgres:15
    networks:
      - hmpps
    container_name: inc-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=incentives
      - POSTGRES_USER=incentives
      - POSTGRES_DB=incentives

networks:
  hmpps:
