info.app:
  name: Hmpps Incentives API
  version: 1.0

feature:
  # Determine how the creation of an IEP review is propagated to other systems.
  # Can be:
  # - 'PRISON_API', an HTTP request to Prison API's `POST /api/bookings/{bookingId}/iepLevels` is made
  # - 'DOMAIN_EVENT', a domain event is published (long term, this will be the preferred/only method)
  #
  # NOTE: Environment variable is `FEATURE_REVIEWADDEDSYNCMECHANISM`
  review-added-sync-mechanism: PRISON_API
  incentives-data-source-of-truth: false

spring:
  application:
    name: hmpps-incentives-api
  codec:
    max-in-memory-size: 10MB
  mvc:
    async:
      request-timeout: 1m
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${api.base.url.oauth}/.well-known/jwks.json

      client:
        registration:
          incentives-api:
            provider: hmpps-auth
            client-id: ${incentives.api.client.id}
            client-secret: ${incentives.api.client.secret}
            authorization-grant-type: client_credentials
        provider:
          hmpps-auth:
            token-uri: ${api.base.url.oauth}/oauth/token

  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  devtools:
    add-properties: false

    data:
      web:
        pageable:
          max-page-size: 20000

  profiles:
    group:
      dev:
        - "localstack"
      test:
        - "localstack"
        - "stdout"

  flyway:
    enabled: true
    url: jdbc:postgresql://${DATABASE_ENDPOINT}/${DATABASE_NAME}?sslmode=verify-full

  r2dbc:
    url: r2dbc:postgresql://${DATABASE_ENDPOINT}/${DATABASE_NAME}
    pool:
      max-life-time: -1
    properties:
      ssl: true
      sslRootCert: /home/appuser/.postgresql/root.crt

api:
  health-timeout-ms: 1000

server:
  port: 8080
  servlet:
    context-path: /
  forward-headers-strategy: native
  netty:
    connection-timeout: 1m
    idle-timeout: 1m
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto
      internal-proxies: 10\.\d{1,3}\.\d{1,3}\.\d{1,3}|192\.168\.\d{1,3}\.\d{1,3}|169\.254\.\d{1,3}\.\d{1,3}|127\.\d{1,3}\.\d{1,3}\.\d{1,3}|172\.1[6-9]{1}\.\d{1,3}\.\d{1,3}|172\.2[0-9]{1}\.\d{1,3}\.\d{1,3}|172\.3[0-1]{1}\.\d{1,3}\.\d{1,3}|0:0:0:0:0:0:0:1|::1|100\.6[4-9]\.\d{1,3}\.\d{1,3}|100\.[7-9][0-9]{1}\.\d{1,3}\.\d{1,3}|100\.1[0-1][0-9]{1}\.\d{1,3}\.\d{1,3}|100\.12[0-7]\.\d{1,3}\.\d{1,3}
  shutdown: graceful
  error:
    include-message: always

hmpps:
  sqs:
    reactiveApi: true
    queueAdminRole: ROLE_INCENTIVES_API_QUEUE_ADMIN

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: 'info, health'
  endpoint:
    health:
      cache:
        time-to-live: 2000ms
      show-components: always
      show-details: always
      probes:
        enabled: true
    info:
      cache:
        time-to-live: 2000ms

azure:
  application-insights:
    web:
      enabled: false
