generic-service:
  replicaCount: 2

  scheduledDowntime:
    enabled: true

  ingress:
    host: incentives-api-preprod.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    API_BASE_URL_OAUTH: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth
    API_BASE_URL_PRISON: https://prison-api-preprod.prison.service.justice.gov.uk
    API_BASE_URL_PRISONER_SEARCH: https://prisoner-search-preprod.prison.service.justice.gov.uk
    API_BASE_URL_LOCATIONS: https://locations-inside-prison-api-preprod.hmpps.service.justice.gov.uk
    # First weekday of the month at 10:00am - Offender Search API is turned off during non-working hours in dev/preprod
    TASK_UPDATE_KPIS_CRON: "0 0 10 1W * *"

generic-prometheus-alerts:
  alertSeverity: hmpps-incentives-preprod
  businessHoursOnly: true
  rdsAlertsDatabases:
    cloud-platform-6b3b723b359a69e2: "incentives api"
  sqsAlertsQueueNames:
    - "hmpps-incentives-preprod-prisoner-event-queue"
    - "hmpps-incentives-preprod-prisoner-event-dlq"
