generic-service:

  ingress:
    host: incentives-api.hmpps.service.justice.gov.uk

  scheduledDowntime:
    enabled: false

  env:
    API_BASE_URL_OAUTH: https://sign-in.hmpps.service.justice.gov.uk/auth
    API_BASE_URL_PRISON: https://prison-api.prison.service.justice.gov.uk
    API_BASE_URL_PRISONER_SEARCH: https://prisoner-search.prison.service.justice.gov.uk
    API_BASE_URL_LOCATIONS: https://locations-inside-prison-api.hmpps.service.justice.gov.uk

  postgresDatabaseRestore:
    enabled: true
    namespace_secrets:
      dps-rds-instance-output:
        DB_NAME: "database_name"
        DB_USER: "database_username"
        DB_PASS: "database_password"
        DB_HOST: "rds_instance_address"
      dps-rds-instance-output-preprod:
        DB_NAME_PREPROD: "database_name"
        DB_USER_PREPROD: "database_username"
        DB_PASS_PREPROD: "database_password"
        DB_HOST_PREPROD: "rds_instance_address"

generic-prometheus-alerts:
  alertSeverity: hmpps-incentives-prod
  rdsAlertsDatabases:
    cloud-platform-4da80b91054a19d6: "incentives api"
  sqsAlertsQueueNames:
    - "hmpps-incentives-production-prisoner-event-queue"
    - "hmpps-incentives-production-prisoner-event-dlq"
