---
# Per environment values which override defaults in hmpps-incentives-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: incentives-api-dev.hmpps.service.justice.gov.uk
  allowlist: null

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    API_BASE_URL_OAUTH: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    API_BASE_URL_PRISON: https://api-dev.prison.service.justice.gov.uk
    API_BASE_URL_OFFENDER_SEARCH: https://prisoner-offender-search-dev.prison.service.justice.gov.uk
    FEATURE_REVIEW_ADDED_SYNC_MECHANISM: "DOMAIN_EVENT"
    FEATURE_INCENTIVES_DATA_SOURCE_OF_TRUTH: true

# CloudPlatform AlertManager receiver to route Prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
  rdsAlertsDatabases:
    cloud-platform-c75ed66addfe4c30: "incentives api"
