---
# Per environment values which override defaults in hmpps-incentives-api/values.yaml

generic-service:

  ingress:
    host: incentives-api.hmpps.service.justice.gov.uk

# CloudPlatform AlertManager receiver to route promethues alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: digital-prison-service
