generic-service:
  replicaCount: 2

  scheduledDowntime:
    enabled: true

  ingress:
    host: incentives-api-dev.hmpps.service.justice.gov.uk

  allowlist: null

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    API_BASE_URL_OAUTH: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    API_BASE_URL_PRISON: https://prison-api-dev.prison.service.justice.gov.uk
    API_BASE_URL_OFFENDER_SEARCH: https://prisoner-search-dev.prison.service.justice.gov.uk
    API_BASE_URL_LOCATIONS: https://locations-inside-prison-api-dev.hmpps.service.justice.gov.uk
    # First weekday of the month at 10:00am - Offender Search API is turned off during non-working hours in dev/preprod
    TASK_UPDATE_KPIS_CRON: "0 0 10 1W * *"

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
  businessHoursOnly: true
  rdsAlertsDatabases:
    cloud-platform-c75ed66addfe4c30: "incentives api"
  sqsAlertsQueueNames:
    - "hmpps-incentives-development-prisoner-event-queue"
    - "hmpps-incentives-development-prisoner-event-dlq"
