---
# Per environment values which override defaults in hmpps-incentives-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: incentives-api-dev.hmpps.service.justice.gov.uk
  allowlist: null

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    API_BASE_URL_OAUTH: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    API_BASE_URL_PRISON: https://api-dev.prison.service.justice.gov.uk
    API_BASE_URL_OFFENDER_SEARCH: https://prisoner-offender-search-dev.prison.service.justice.gov.uk

  namespace_secrets:
    hmpps-incentives-api:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      INCENTIVES_API_CLIENT_ID: "INCENTIVES_API_CLIENT_ID"
      INCENTIVES_API_CLIENT_SECRET: "INCENTIVES_API_CLIENT_SECRET"
    dps-rds-instance-output:
      SPRING_FLYWAY_USER: "database_username"
      SPRING_FLYWAY_PASSWORD: "database_password"
      SPRING_R2DBC_USERNAME: "database_username"
      SPRING_R2DBC_PASSWORD: "database_password"
      DATABASE_NAME: "database_name"
      DATABASE_ENDPOINT: "rds_instance_endpoint"
    hmpps-domain-events-topic:
      HMPPS_SQS_TOPICS_DOMAINEVENTS_ACCESS_KEY_ID: "access_key_id"
      HMPPS_SQS_TOPICS_DOMAINEVENTS_SECRET_ACCESS_KEY: "secret_access_key"
      HMPPS_SQS_TOPICS_DOMAINEVENTS_ARN: "topic_arn"
    sqs-hmpps-audit-secret:
      HMPPS_SQS_QUEUES_AUDIT_QUEUE_ACCESS_KEY_ID: "access_key_id"
      HMPPS_SQS_QUEUES_AUDIT_QUEUE_SECRET_ACCESS_KEY: "secret_access_key"
      HMPPS_SQS_QUEUES_AUDIT_QUEUE_NAME: "sqs_queue_name"
    sqs-prisoner-event-queue-secret:
      HMPPS_SQS_QUEUES_INCENTIVES_QUEUE_ACCESS_KEY_ID: "access_key_id"
      HMPPS_SQS_QUEUES_INCENTIVES_QUEUE_SECRET_ACCESS_KEY: "secret_access_key"
      HMPPS_SQS_QUEUES_INCENTIVES_QUEUE_NAME: "sqs_queue_name"
    sqs-prisoner-event-queue-dlq-secret:
      HMPPS_SQS_QUEUES_INCENTIVES_DLQ_ACCESS_KEY_ID: "access_key_id"
      HMPPS_SQS_QUEUES_INCENTIVES_DLQ_SECRET_ACCESS_KEY: "secret_access_key"
      HMPPS_SQS_QUEUES_INCENTIVES_DLQ_NAME: "sqs_queue_name"

# CloudPlatform AlertManager receiver to route Prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
  rdsAlertsDatabases:
    cloud-platform-c75ed66addfe4c30: "incentives api"
  sqsAlertsQueueNames:
    - "Digital-Prison-Services-dev-hmpps_incentives_queue"
    - "Digital-Prison-Services-dev-hmpps_incentives_dlq"
